# prometheus.yml

global:
  scrape_interval:     15s
  evaluation_interval: 30s
  # scrape_timeout is set to the global default (10s).

scrape_configs:
- job_name: fastapi
  honor_labels: true
  static_configs:
  - targets:
    - hk-fastapi-monitoring  # metrics from model
- job_name: 'jenkins'
  metrics_path: /prometheus/
  static_configs:
    - targets:
      - "http://ec2-15-168-66-215.ap-northeast-3.compute.amazonaws.com:8080"